### ISSUE TITLE
Did you end up setting up an adruino to control these?

### ISSUE THREAD

**Issue by jacebenson** [CXgamer/Aura-sync-splitter#1]
I followed along in your thread https://rog.asus.com/forum/showthread.php?96095-Adding-more-AURA-RGB-headers/page3

 But the end seems... disappointing.  I am working on a similar requirement and if you could share how you configured your arduino it could be helpful to me.  I'm running on a Raspberrypi using this at the moment.
https://learn.adafruit.com/tlc5947-tlc59711-pwm-led-driver-breakout/python-circuitpython

**Comment by Breina** [comment]
I didn't end up using an Arduino and just left it in my motherboard. In principle, since Aura talks to these RGB outputs, other software should be able to do this as well.

There's [great progress made by CalcProgrammer1](https://gitlab.com/CalcProgrammer1/OpenAuraSDK/wikis/home) on reverse engineering its protocol, so that's something to look forward to.

If you want to steer it from your RPi anyway, [it's perfectly possible](https://tutorials-raspberrypi.com/connect-control-raspberry-pi-ws2812-rgb-led-strips/), no Arduino needed. PWM won't help you with this.

Arduino works as well, you just need to look for a WS2811b control program and you're set. Good luck!

**Comment by jacebenson** [comment]
I was hoping to use the Aura interface but It sounds like that's a no go.  I'll mess with the setup I have and just have to deal with two controls for lights.  Maybe I can read the data from the output pins of the mobo to trigger the patterns at least.  I'll make a new issue with what I end up doing.  Thanks for your fast response CX.

**Comment by nirim000** [comment]
sorry for that bit of necroposting here but, [FastLED](https://github.com/FastLED/FastLED) work very well, you could connect a inexpensive arduino compatible boar with 3.3v logic directly to the rpi gpio or by usb, depending on your use case and use a python script to control it via UART, i recommend the Blue Pill.
